name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'  # Ensure submodules are properly initialized

      - name: Initialize Submodules
        run: git submodule update --init --recursive

      - name: Print Directory Structure
        run: find . -name gtest.h

      - name: Build GoogleTest
        run: |
          mkdir googletest/build
          cd googletest/build
          cmake ..
          cmake --build .
          cd ../..

      - name: Build and Run Tests
        run: |
          g++ -std=c++17 -Igoogletest/googletest/include -Lgoogletest/build/lib -lgtest -lgtest_main *.cpp -o test_executable
          ./test_executable
