name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install GoogleTest
      run: |
        sudo apt-get update
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib

    - name: Build and Run Tests
      run: |
        g++ -std=c++17 -Igoogletest/googletest/include -Lgoogletest/build/lib -lgtest -lgtest_main *.cpp -o test_executable
        ./test_executable
