name: CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'  # Ensure submodules are properly initialized

    - name: Initialize Submodules
      run: git submodule update --init --recursive

    - name: Print Directory Structure
      run: |
        pwd
        ls -la
        ls -la googletest

    - name: Create Build Directory
      run: |
        mkdir -p /home/runner/work/SE320OpenSource/SE320OpenSource/googletest/build

    - name: Build GoogleTest
      run: |
        cd googletest/build
        cmake ..
        cmake --build .
        cd ../..

    - name: Change Permissions
      run: |
        sudo chmod -R 777 /home/runner/work/SE320OpenSource/SE320OpenSource/googletest/build

    - name: Copy GoogleTest Build
      run: |
        cp -r googletest/build /home/runner/work/SE320OpenSource/SE320OpenSource/build/

    - name: Build and Run Tests
      run: |
        g++ -std=c++17 -I/Users/cformanek/Documents/SE320/SE320OpenSource/googletest/googletest/include/gtest -L/home/runner/work/SE320OpenSource/SE320OpenSource/build/lib -lgtest -lgtest_main *.cpp -o test_executable
        ./test_executable
