name: C++ Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev mlocate

    - name: Find GTest include directory
      run: |
        GTEST_INCLUDE_DIR=$(dirname $(locate -r '/gtest\.h$'))

    - name: Build
      run: |
        g++ -std=c++17 -I $GTEST_INCLUDE_DIR -L /usr/lib -lgtest -lgtest_main -pthread *.cpp -o test

    - name: Run tests
      run: ./test
