name: CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print Directory Contents
      run: |
        ls -la

    - name: Copy GoogleTest Build
      run: |
        cp -r googletest/build /usr/local/

    - name: Build and Run Tests
      run: |
        g++ -std=c++17 -Igoogletest/googletest/include -L/usr/local/build/lib -lgtest -lgtest_main *.cpp -o test_executable
        ./test_executable
