name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev

    - name: Build
      run: |
        g++ -std=c++17 -I /usr/include -I /usr/src/gtest -L /usr/lib -lgtest -lgtest_main -pthread *.cpp -o test

    - name: Run tests
      run: ./test
