name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        g++ -std=c++17 -I /usr/include -I googletest/googletest/include -L /usr/lib -lgtest -lgtest_main -pthread *.cpp -o test

    - name: Run tests
      run: ./test
